3week


import sys, serial,time

cmd='temp'
seri=serial.Serial('dev/ttyACM0',9600,timeout=5)
print(seri)

seri.write(cmd.encode())

while(True):
    if seri.in_waiting>0:
        content=seri.readline()
        print(content[:],decode())
        time.sleep(1)
        
        
error

>> %Run aaaa.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 322, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
FileNotFoundError: [Errno 2] No such file or directory: 'dev/ttyACM0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/inha/aaaa.py", line 4, in <module>
    seri=serial.Serial('dev/ttyACM0',9600,timeout=5)
  File "/usr/lib/python3/dist-packages/serial/serialutil.py", line 244, in __init__
    self.open()
  File "/usr/lib/python3/dist-packages/serial/serialposix.py", line 325, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 2] could not open port dev/ttyACM0: [Errno 2] No such file or directory: 'dev/ttyACM0'
>>> 
